---
- name: Get Wowza
  get_url: url={{ wowza_download_url }} dest=/opt/src/{{ wowza_installer }} mode=0755
- name: install expect
  apt: name={{ item }} update_cache=yes
  with_items: 
    - expect
    - expect-dev
- name: push expect templates
  template: src=script.exp.j2 dest=/opt/src/script.exp mode=0755
- name: Run expect script, which runs Wowza installer
  args:
    creates: /usr/local/WowzaStreamingEngine/conf/Server.license
  shell: /opt/src/script.exp
